### ISSUE TITLE
Overriding HTML files doesn't work

### ISSUE THREAD

**Issue by kelunik** [ExLibrisGroup/primo-explore-package#1]
I have a working [`devenv`](https://github.com/ExLibrisGroup/primo-explore-devenv), editing the CSS works fine. But replacing the HTML files doesn't work.

```
primo-explore/custom/KIT/
├── css
│   ├── custom1.css
│   └── README.md
├── html
│   ├── homepage
│   │   └── homepage_en_US.html
│   └── README.md
├── img
│   └── README.md
├── js
│   ├── custom.js
│   └── README.md
├── README.md
└── showDirectives.txt
```

Moving `homepage_en_US.html` to a `homepage` directory makes at least the logged JSON seem to be right:

```yml
{ viewJs: [ 'custom/KIT/js/custom.js' ],
  viewCss: [ 'custom/KIT/css/custom1.css' ],
  centralCss: '',
  favIcon: [],
  libraryLogo: undefined,
  resourceIcons: {},
  homepageHtml: '',
  staticHtml: 
   { homepage: 
      { en_US: 'custom/KIT/html/homepage/homepage_en_US.html',
        default: 'custom/KIT/html/homepage/homepage_en_US.html' } } }
```

Without the move, it looks like that:

```yml
{ viewJs: [ 'custom/KIT/js/custom.js' ],
  viewCss: [ 'custom/KIT/css/custom1.css' ],
  centralCss: '',
  favIcon: [],
  libraryLogo: undefined,
  resourceIcons: {},
  homepageHtml: '',
  staticHtml: 
   { 'custom/KIT/html/homepage': 
      { en_US: 'custom/KIT/html/custom/KIT/html/homepage/custom/KIT/html/homepage_en_US.html',
        default: 'custom/KIT/html/custom/KIT/html/homepage/custom/KIT/html/homepage_en_US.html' } } }
```

What we really want to replace is the following HTML file: `search/fullView/details/service-details.html`. How does the required folder structure look like?

I found an example at https://github.com/noamamit92/primo-explore-altmetrics-widget, but that doesn't replace the HTML files.
